lattice_planner_node:
  ros__parameters:
    track_specifier: 'skirkanich_front_sunday'
    toppath: '/sim_ws/src/lattice_planner_pkg'
    mappath: '/sim_ws/src/f1tenth_gym_ros/maps/skirkanich_front_sunday'
    odometry_topic: '/ego_racecar/odom'
    trajectory_topic: '/lattice_planner/local_traj'
    opponent_list_topic: '/opponent_detect/opponent_list'
    global_trajectory_topic: '/lattice_planner/global_traj'
    toppath_topic: '/lattice_planner/toppath'
    map_spec_topic: '/lattice_planner/map_specifier'
    global_traj_vis_topic: '/lattice_planner/global_traj_vis_topic'
    local_traj_vis_topic: '/lattice_planner/local_traj_vis_topic'
    visual_mode: False
    log_mode: False
    publish_global: False
    yaw_offset: -1.5708
    start_vel: 3.0
    opponent_length: 0.5
    opponent_width: 0.3

pure_pursuit_node:
  ros__parameters:
    sparse_waypoint_filename: 'traj_race_cl_skirkanich4'
    drive_topic: '/drive'
    trajectory_topic: '/lattice_planner/local_traj'
    global_trajectory_topic: '/lattice_planner/global_traj'
    odometry_topic: '/ego_racecar/odom'
    waypoint_vis_topic: '/pure_pursuit/waypoint'
    lookahead_method: 'curvature'
    use_global_traj: False
    steering_angle_bound: 0.4
    desired_speed: 4.5
    min_speed: 1.0
    proportional_control: 0.8
    steering_angle_factor: 0.6
    speed_factor: 1.0
    waypoint_distance: 0.1
    min_lookahead: 1.2
    max_lookahead: 1.6

object_detect_node:
  ros__parameters:
    odometry_topic: '/ego_racecar/odom'
    laserscan_topic: '/scan'
    obstacle_vis_topic: '/opponent_detect/obstacle_vis'
    clusters_vis_topic: '/opponent_detect/clusters_vis'
    toppath_topic: '/lattice_planner/toppath'
    map_spec_topic: '/lattice_planner/map_specifier'
    opponent_list_topic: '/opponent_detect/opponent_list'
    lidar_proc_max_dist: 10.0
    gap_threshold: 1.5
    lambda: 0.1047
    sigma: 0.05
    bound_offset: 0.2 
    opponent_offset_x: 0.2
    opponent_offset_y: 0.0 

waypoint_logger_service:
  ros__parameters:
    odometry_topic: '/ego_racecar/odom'
    lidar_scan_topic: '/scan'
    log_filepath: '/sim_ws/src/lattice_planner_pkg/inputs/waypoints/sample_filename.csv'

