lattice_planner_node:
  ros__parameters:
    track_specifier: 'skirkanich2'
    toppath: '/sim_ws/src/lattice_planner_pkg'
    mappath: '/sim_ws/src/f1tenth_gym_ros/maps/skirkanich_front_friday'
    odometry_topic: '/ego_racecar/odom'

pure_pursuit_node:
  ros__parameters:
    lookahead_distance: 1.2
    steering_angle_bound: 0.4
    desired_speed: 4.5
    min_speed: 1.0
    proportional_control: 1.0
    steering_angle_factor: 0.6
    speed_factor: 1.0
    sparse_waypoint_filename: 'global_trajectory'
    waypoint_distance: 0.1

waypoint_logger_service:
  ros__parameters:
    odometry_topic: '/ego_racecar/odom'
    lidar_scan_topic: '/scan'
    log_filepath: '/sim_ws/src/lattice_planner_pkg/inputs/waypoints/sample_filename.csv'

